Eventbrite/config/routes.rb
Rails.application.routes.draw do
  root to: 'event#index'
  get 'home/secret'
  devise_for :users
  resources :users
  resources :avatars, only: [:create]
  resources :event
  resources :charges
end

Eventbrite/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Eventbrite/app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

Eventbrite/app/models/event.rb
class Event < ApplicationRecord

  validates :start_date, presence: true
  validates :duration, presence: true
  validates :title, presence: true, length: {in: 5..10}
  validates :description, presence: true, length: {in: 20..1000}
  validates :price, presence: true, length: {in: 1..1000}
  validates :location, presence: true

  has_many :attendances
  has_many :users, through: :attendances
end

Eventbrite/app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :attendances
  has_many :events, through: :attendances
end

Eventbrite/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Eventbrite/app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def create
    @user = User.find(params[:format])
    @user.avatar.attach(params[:avatar])
    redirect_to(user_path(@user))
  end
end

Eventbrite/app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def show
    @all_u = User.all
    @event_id = params[:id].to_i
    @@event_id_to = @event_id
    @all_e = Event.all
  end

  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )
    # puts current_user.id
    # puts customer.id
    # puts @@event_id_to

    @a = Attendance.create(user_id: current_user.id, event_id: @@event_id_to, strip_custumer_id: customer.id)


    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

end

Eventbrite/app/controllers/event_controller.rb
class EventController < ApplicationController
  before_action :authenticate_user!

  def index
    @all_e = Event.all
  end

  def new
    @e = Event.new
  end

  def create
    @user = User.find(current_user.id)
    @id_current_user = current_user.id
    event = Event.create(title: params[:title], description: params[:description], location: params[:location], start_date: params[:start_date], duration: params[:duration], price: params[:price], user_id: @id_current_user)
    @user.events << event
    @user.save
    redirect_to event_index_path
end

  def show
    @all_u = User.all
    @event_id = params[:id].to_i
    @@event_id_to = @event_id
    @all_e = Event.all
    @attendance = Attendance.all
  end

  # private
  # def authenticate_user
  #   unless current_user
  #     flash[:danger] = "Please log in."
  #     redirect_to root_path
  #   end
  # end
end

Eventbrite/app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authenticate_user!, only: [:secret]

  def index
    #redirect_to event_index_path
  end

  def secret
  end
end

Eventbrite/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end
  def show
    @current_user =  User.find(current_user.id)
    @event = Event.where(user_id: current_user.id)
  end

  def edit
    @current_user = User.find(current_user.id)
  end

  def update
    @current_user = User.find(current_user.id)
    user_params =  params.require(:user).permit(:first_name, :last_name, :description)
    @current_user.update(user_params)
    redirect_to user_path(current_user.id)
  end
end

Eventbrite/app/helpers/application_helper.rb
module ApplicationHelper
end

Eventbrite/app/helpers/avatars_helper.rb
module AvatarsHelper
end

Eventbrite/app/helpers/charges_helper.rb
module ChargesHelper
end

Eventbrite/app/helpers/home_helper.rb
module HomeHelper
end

Eventbrite/app/views/charges/create.html.erb
<h2>Thanks, you paid !</h2>
<%= link_to "Back to home", root_path%>

Eventbrite/app/views/charges/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>


    <h1>affichage d'un event que tu voudrais bien y participer</h1>
        <%@all_e.each do |e|%>

            <%if e.id==(@event_id)%>
            <%@all_u.each do |u|%>
              <%if u.id == e.user_id%>
                c'est <%=u.first_name%> qui a créer : <br>
                <b>titre de l'event :</b>
                <%=e.title%><br>
                <b>Description de l'event :</b>
                <%=e.description%><br>
                <b>Localisation de l'event :</b>
                <%=e.location%><br>
                <b>Date de début :</b>
                <%=e.start_date%><br>
                <b>Durée :</b>
                <%=e.duration%>
                <b>minutes</b><br>
                <b>Prix :</b>
                <%=@price = e.price%><br>
              <%end%>
        <%end%>
        <%if e.user_id == current_user.id%>
        <!--si current user est le createur de l'event on affiche pas payer-->
        <b><p>tu ne peux pas participer puisque tu en est l'auteur</p></b>
        <%else%><br>
          <!---->
          <%= form_tag charges_path do %>
            <article>
              <% if flash[:error].present? %>
                <div id="error_explanation">
                  <p><%= flash[:error] %></p>
                </div>
              <% end %>
              </article>
            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                    data-description="payed an envent"
                    data-amount=<%=@price%>
                    data-event-id=<%=@event_id%>
                    data-locale="auto">
            </script>
          <%end%>

        <%end%>
     <%end%>
   <%end%><br>


    <%=link_to "Back to home", root_path%><br>
  </body>
</html>

Eventbrite/app/views/event/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
      <p>bonjour : <a href="<%=user_path(current_user.id)%>"><%= current_user.email %></a></p>
      <h1>Ici les events</h1>
      <%@all_e.each do |e|%><br>
        <a href="<%=event_path(e.id)%>"><%=e.title%></a>
        <%=e.start_date%>
      <%end%><br><br>

      <%= link_to "Créer un Evenement", new_event_path%><br>
      <%= link_to "Edit email / password", edit_user_registration_path %><br>
      <%=link_to "Sign out", destroy_user_session_path, method: :delete %><br>

  </body>
</html>

Eventbrite/app/views/event/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

      <h1>Ici creation des events</h1>
      <form accept-charset="UTF-8" action="<%=event_index_path%>" method="post">
      <%= token_tag %>
      <input name="utf8" type="hidden" value="&#x2713;"/>
      start_date:
      <input type='date' name='start_date'/><br/>
      duration:
      <input type='integer' name='duration'/><br/>
      title:
      <input type='text' name='title'/><br/>
      description:
      <input type='textarea' name='description'/><br/>
      price:
      <input type='integer' name='price'/><br/>
      location:
      <input type='text' name='location'/><br/>

      <input type='submit'/><br>

      <%=link_to "Back", event_index_path%>
  </body>
</html>

Eventbrite/app/views/event/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <%=current_user.first_name%>  id :<%=current_user.id%><br>
    event_id :<%=@event_id%>
    <h1>affichage d'un event precis</h1>
        <%@all_e.each do |e|%>
          <%if e.id==(@event_id)%>
            <%@all_u.each do |u|%>
              <%if u.id == e.user_id%>
                c'est <%=u.first_name%> qui a créer : <br>
                <b>titre de l'event :</b>
                <%=e.title%><br>
                <b>Description de l'event :</b>
                <%=e.description%><br>
                <b>Localisation de l'event :</b>
                <%=e.location%><br>
                <b>Date de début :</b>
                <%=e.start_date%><br>
                <b>Durée :</b>
                <%=e.duration%>
                <b>minutes</b><br>
                <b>Prix :</b>
                <%=@price = e.price%><br>
              <%end%>
            <%end%>
          <%end%>
        <%end%>
        <br>


    <a href="<%=charge_url(@event_id)%>">Participer</a><br>
    <%=link_to "Sign out", destroy_user_session_path, method: :delete %><br>
    <%=link_to "Back", event_index_path%><br>
  </body>
</html>

Eventbrite/app/views/home/index.html.erb
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Créer un Evenement", new_event_path%>
    </li>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>
    <li>
      Voici ton email :
      <%= current_user.email %>
    </li>
    <li>
      <%= link_to "Secret page", home_secret_path %>
    </li>
    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>
  <% else %>
    <li>
      <%= link_to "Sign in", new_user_session_path %>
    </li>
    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>
  <% end %>
</ul>

Eventbrite/app/views/home/secret.html.erb
<h1>Home#secret</h1>
<p>Find me in app/views/home/secret.html.erb</p>

Eventbrite/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Eventbrite/app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

Eventbrite/app/views/users/edit.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Edition du profil de <%=current_user.email%></h1>
    <%= form_for @current_user do |f| %>
    <div class="">
      <label for="">Nom:</label>
      <%= f.text_field :first_name%><br>
      <label for="">Prénom:</label>
      <%= f.text_field :last_name%><br>
      <label for="">Description:</label>
      <%= f.text_field :description%>
      <button type="submit">update_current_user</button>
    </div>
    <%end%>

    <%=link_to "Back", event_index_path%>
  </body>
</html>

Eventbrite/app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

Eventbrite/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

Eventbrite/app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body><br>
  <h1>affichage current profil</h1>
      <%if @current_user.avatar.attached?%>
        <%= image_tag @current_user.avatar, alt: 'avatar' %>
      <%else%>
        <p>=== Il n'y a pas encore d'avatar lié à cet utilisateur ===</p>
      <%end%><br><br>
      <h3>Changer d'avatar ?</h3>
      <%= form_tag avatars_path(@current_user), multipart: true do %>
        <%= file_field_tag :avatar %>
        <%= submit_tag "mettre à jour" %>
      <% end %><br><br>

    ton email est :
    <%= current_user.email %><br>
    ton prénom est :
    <%= current_user.first_name %><br>
    ton nom est :
    <%= current_user.last_name %><br>
    A propos :
    <%= current_user.description %><br><br>
    les events que tu as créer :

    <%@event.each do |e|%><br>
      <%=e.title%>
    <%end%>
    <br><br>
    <%=link_to "edit profil", edit_user_path%><br>
    <%=link_to "Back", event_index_path%>
  </body>
</html>